path_data: './data/500b_v3.csv'
path_log: './result/result_log.csv'

# ID của thí sinh
ID: 1

# learning rate
lr: 0.01

# khoảng cách tối đa giữa câu hỏi lấy ra và theta hiện tại
eps: 0.05

# Số câu tối đa cần trả lời
K: 100

# Số câu trả lời đúng liên tiếp thì lấy ra câu khó nhất và break
max_seq_right: 15

# Số câu trả lời sai liên tiếp thì lấy ra câu dễ nhất chưa trả lời
max_seq_wrong: 5

# Số câu trả lời liên tiếp mà theta không thay đổi nhiều thì lấy ra câu hỏi khó nhất và break
max_seq_theta: 10

# ngưỡng theta phải thay đổi sau một số câu hỏi liên tiếp
eps_theta: 1
